# Generated by Django 5.1 on 2024-08-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('skuNumber', models.CharField(max_length=255)),
                ('itemDescription', models.TextField()),
                ('poNumber', models.CharField(max_length=255)),
                ('qtyPieces', models.IntegerField()),
                ('factoryName', models.CharField(max_length=255)),
                ('inspectedBy', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('inspectionResult', models.CharField(max_length=255)),
                ('constructionSteps', models.JSONField(default=dict)),
                ('assemblySteps', models.JSONField(default=dict)),
                ('cartonDetails', models.JSONField(default=dict)),
                ('cartonLength', models.FloatField()),
                ('cartonWidth', models.FloatField()),
                ('cartonWeight', models.FloatField()),
                ('grossWeight', models.FloatField()),
                ('netWeight', models.FloatField()),
            ],
        ),
    ]
